// <auto-generated />
using System;
using AplicacionTareas.Infrastructure.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplicacionTareas.Infrastructure.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    [Migration("20260714085544_AgregarVencimientoTarea")]
    partial class AgregarVencimientoTarea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AplicacionTareas.Domain.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActualizadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaCompletada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VenceEnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstaCompletada")
                        .HasDatabaseName("IX_Tareas_EstaCompletada");

                    b.HasIndex("Titulo")
                        .HasDatabaseName("IX_Tareas_Titulo");

                    b.HasIndex("VenceEnUtc")
                        .HasDatabaseName("IX_Tareas_VenceEnUtc");

                    b.ToTable("Tareas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
