// <auto-generated />
using System;
using AplicacionTareas.Infrastructure.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplicacionTareas.Infrastructure.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    [Migration("20260716084212_AgregarDepartamentosYDepartamentoUsuario")]
    partial class AgregarDepartamentosYDepartamentoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AplicacionTareas.Domain.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActualizadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Departamentos_Nombre");

                    b.ToTable("Departamentos", (string)null);
                });

            modelBuilder.Entity("AplicacionTareas.Domain.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActualizadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaCompletada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioAsignadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VenceEnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_Tareas_Categoria");

                    b.HasIndex("EstaCompletada")
                        .HasDatabaseName("IX_Tareas_EstaCompletada");

                    b.HasIndex("Titulo")
                        .HasDatabaseName("IX_Tareas_Titulo");

                    b.HasIndex("UsuarioAsignadoId")
                        .HasDatabaseName("IX_Tareas_UsuarioAsignadoId");

                    b.HasIndex("VenceEnUtc")
                        .HasDatabaseName("IX_Tareas_VenceEnUtc");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("AplicacionTareas.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActualizadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId")
                        .HasDatabaseName("IX_Usuarios_DepartamentoId");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Usuarios_Nombre");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AplicacionTareas.Domain.Usuario", b =>
                {
                    b.HasOne("AplicacionTareas.Domain.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("AplicacionTareas.Domain.Departamento", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
